<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\Р СњР С•Р Р†Р В°РЎРЏ Р С—Р В°Р С—Р С”Р В°\**" />
    <Content Remove="Services\Р СњР С•Р Р†Р В°РЎРЏ Р С—Р В°Р С—Р С”Р В°\**" />
    <EmbeddedResource Remove="Services\Р СњР С•Р Р†Р В°РЎРЏ Р С—Р В°Р С—Р С”Р В°\**" />
    <None Remove="Services\Р СњР С•Р Р†Р В°РЎРЏ Р С—Р В°Р С—Р С”Р В°\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2025.12.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodPreOrder.Application\FoodPreOrder.Application.csproj" />
    <ProjectReference Include="..\FoodPreOrder.Infrastructure\FoodPreOrder.Infrastructure.csproj" />
    <ProjectReference Include="..\FoodPreOrder.Persistence\FoodPreOrder.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

</Project>
